/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-106313-g31916d3d9f-20220318"
#endif /* AVUTIL_FFVERSION_H */
